# 1.简介
与普通函数不同的是，调用generator函数后，该函数并不执行，返回的也不是结果，而是一个指向内部状态的指针对象，即**遍历器对象**。

下一步，必须调用**next**方法，使得指针移向下一个状态。也就是说，每次调用next方法，内部指针就从函数头部或上一次停下来的地方开始执行，直到遇到下一个yield表达式，

## yield表达式
由于Generator函数返回的遍历器对象，只有调用next方法才会遍历下一个内部状态，所以其实提供了一个可暂停执行的函数，yield就是暂停标志。
遍历器对象的**next**方法运行逻辑如下：
- [ ] 遇到**yield**表达式，就暂停后面的操作，并将紧跟在**yield**后面的表达式的值，作为返回对象的**value**属性值。
- [ ] 下一次调用next方法时，再继续往下执行，知道遇到下一个**yield**表达式。
- [ ] 如果没有再遇到新的yield表达式，就一直运行到函数结束，知道return语句为止，并将return语句后面的表达式的值，作为返回对象的value属性值。
- [ ] 如果该函数没有return语句，则返回的对象的value值为undefined。

## 与Iterator接口的关系
任意一个对象的**Symbol.Iterator**方法，等于该对象的遍历器生成函数，调用该函数会返回该对象的一个遍历器对象。

由于**Generator**函数就是遍历器生成函数，因此可以把**Generator**函数赋值给对象的**Symbol.Iterator**属性，从而使得该对象具有**Iterator**接口。
```javascript
var myIterable = {}
myIterable[Symbol.Iterator] = function* (){
  yield 1,
  yield 2,
  yield 3
}
[...myIterable]
```

# 2.next方法的参数
**yield**表达式本身没有返回值，或者说总是返回undefined。next方法可以带一个参数，该参数就会被当成上一个**yield**表达式的返回值。
```javascript
function* gen(){
  console.log('Started')
  console.log(`1.${yield}`)
  console.log(`2.${yield}`)
  return 'result'
}

let genObj = gen()
genObj.next()
genObj.next('hello')
genObj.next('world')
```
# 3.for…of循环
**for**…**of**循环可以自动遍历调用**Generator**函数时生成的**Iterator**对象，且此时不再需要调用next()方法。

使用Generator函数实现的斐波那契数列：
```javascript
function* fibonacci(){
  let [prev, curr] = [0, 1]
  for(;;){
    [prev, curr] = [curr, prev+curr]
    yield curr
  }
}

for(let n of fibonacci){
  if(n>1000) break
  console.log(n)
}
``` 
原生的JavaScript对象是没有遍历接口的，无法使用for…of循环，通过**Generator**函数为它加上这个接口，就可以用了。
# 4.Generator.prototype.throw()
Generator函数返回的遍历器对象，都有一个throw方法，可以在函数体外抛出错误，然后在Generator函数体内捕获。
```javascript
function* gen(){
	try{
		yield
	}catch(e){
		console.log('内部捕获',e)
	}
}

let genObj = gen()
genObj.next()

try{
	genObj.throw('a')
	genObj.throw('b')
}catch(e){
	console.log('外部捕获',e)
}
// 内部捕获，a
// 外部捕获，b
```
**注意**，不要混淆遍历器对象的throw方法和全局的throw命令。上面代码的错误是遍历器对象的throw方法抛出的，而不是用throw命令抛出的。后者只能被函数体外的catch捕获。

throw方法被捕获后，会附带执行下一条yield表达式。也就是说，会附带执行一次next方法。
```javascript
var gen = function* gen(){
  try{
		yield console.log('a')
	}catch(e){
		// ...
	}
	yield console.log('b')
	yield console.log('c')
}

var g = gen()
g.next() //a
g.throw() //b
g.next() //c
```

一旦**Generator**函数在执行过程中抛出错误，且没有被内部捕获，就不会再执行下去了。如果此后还调用**next**方法，将返回一个**value**属性等于**undefined**、**done**等于**true**的对象，即JavaScript引擎以为这个Generator已经执行结束了。
```javascript
function* gen(){
	yield 1
	console.log('throwing an exception')
	throw new Error('generator broke!')
	yield 2
	yield 3
}

function log(generator){
	var v
	console.log('starting generator')
	try{
		v = generator.next()
		console.log('第一次运行next方法',v)
	}catch(err){
		console.log('捕捉错误',v)
	}
	try{
		v = generator.next()
		console.log('第二次运行next方法',v)
	}catch(err){
		console.log('捕捉错误',v)
	}
	try{
		v = generator.next()
		console.log('第三次运行nextfangfa',v)
	}catch(err){
		console.log('捕捉错误',v)
	}
	console.log('caller done')
}

log(gen())
// starting generator
// 第一次运行next方法 { value: 1, done: false }
// throwing an exception
// 捕捉错误 { value: 1, done: false }
// 第三次运行next方法 { value: undefined, done: true }
// caller done
```
# 5.Generator.prototype.return()
Generator返回的遍历器对象，还有一个return方法，可以返回给定的值，并且终结遍历Generator函数。
```javascript
function* gen(){
  yield 1
  yield 2
  yield 3
}

var genObj = gen()
genObj.next() //{value: 1, done: false}
genObj.return(4)  //{value: 4, done: true}
genObj.next()  //{value: undefined, done: true}
```
如果Generator函数内部有try…finally代码库，那么return方法会推迟到finally代码块执行完再执行。
```javascript
function* gen(){
  yield 1
  try{
    yield 2
    yield 3
  }finally{
    yield 4
    yield 5
  }
  yield 6
}

var genObj = gen()
genObj.next()  //{value: 1, done: false}
genObj.next()  //{value: 2, done: false}
genObj.return(7)  //{value: 4,done: false}
genObj.next()  //{value: 5, done: false}
genObj.next()  //{value: undefined, done: true}
```
上面代码中，调用return方法后，就开始执行finally代码块，然后等到finally代码块执行完，再执行return方法。
# 6.next()、throw()、return()的共同点
这三种方法本质上是相同的，作用都是让Generator方法恢复执行，并且使用不同的语句替换yield表达式。
```javascript
function* gen(x, y){
  let result = yield x + y
  return result
}
const genObj = gen(1, 2)
genObj.next() //{value: 3, done: false}
genObj.next(1) //{value: 1, done: true}
// 相当于将let result = yield x + y
// 替换成 let result = 1 
```
# 7.yield*表达式
如果在**Generator**函数内部，调用另一个**Generator**函数，需要使用**yield***表达式。
```javascript
function* foo(){
	yield 2
	yield 3
	return 'foo'
}
function* bar(){
	yield 1
	var v = yield* foo()
	console.log('v:'+v)
	yield 4
}
var it = bar()
it.next()
// {value: 1, done: false}
it.next()
// {value: 2, done: false}
it.next()
// {value: 3, done: false}
it.next()
// v: foo
// {value: 4, done: false}
```
**注意**，foo的返回值被传递给了bar的内部的 result变量，所以被打印出来了；一旦next方法的返回对象的done属性为true，for...of循环就会中止，且不包含该返回对象。