# 1.含义
**async**函数作为**generator**的语法糖，将generator函数的**星号**(*)换成**async**，**yield**替换成**await**。
>async函数对generator函数的改进主要体现在以下四点：
1. 内置执行器。一旦调用了async函数之后，会自动执行，直到输出结果。而generator可能更多的依赖于co模块或者Thunk函数。
2. 更好的语义。async和await的语义相当清楚。
3. 更广的适用性。co模块规定，yield后面只能是Thunk函数或Promise对象，而async函数中await后面，可以是promise对象和原始类型的值。
4. 返回值是Promise对象。相比之下，generator返回的值是Iterator对象。你可以用then方法指定下一步的操作。

进一步说，**async**函数可以看成是多个异步操作，包装成的一个Promise对象，而**await**命令就是内部then命令的语法糖。

# 2.基本用法

# 3.用法
### **async**函数返回一个Promise对象。
**async**函数内部**return**语句返回的值，会成为**then**方法回调函数的参数。

### **Promise**对象的状态变化
async函数返回的Promise对象，必须等内部所有await后面的Promise对象执行完，才会发生状态改变，除非遇到return语句或抛出错误。

### **await命令**
正常情况下，await命令后面是一个Promise对象。如果不是，会被转化成一个立即resolve的Promise对象。

**await**命令后面的**Promise**对象如果变为**reject**状态，则**reject**的参数会被**catch**方法的回调函数接收到。并且只要有一个**await**语句变为**reject**，那么整个**async**函数都会中断执行。
```javascript
async function func(){
  await Promise.reject('出错了')
  return await Promise.resolve('hello world') //不会执行
}

func()
.then(data => {console.log(data)})
.catch(err => {console.log(err)})
```
有时，我们希望即使前一个异步操作失败，也不要中断后面的异步操作。

第一种方法：
```javascript
async function func(){
  try{
    await Promise.reject('error')
  }catch(e){
  }
  return await Promise.resolve('hello world')
}

func().then(console.log)
```
第二种方法：
```javascript
async function func(){
  await Promise.reject('error').catch(console.log)
  return await Promise.resolve('hello world')
}

func().then(console.log)
```
### 错误处理
如果await后面的异步操作出错，那么等同于async函数返回的Promise对象被reject。
```javascript
async function func(){
  await new Promise((resolve,reject)=> {
    throw new Error('error')
  })
}

func()
.then(v => console.log(v))
.catch(e => console.log(e))
```
防止出错的方法，就是将其放在try…catch代码块之中。
### 使用注意点
1. await后面的Promise对象，运行结果可能是rejected，所以最好把await命令放在try...catch代码块中，或者添加.catch方法来提前截取到rejected对象。

2. 多个await命令后面的异步操作，如果不存在继发关系，最好同时触发。
```javascript
let foo = await getFoo()
let bar = await getBar() 
```
这两个独立的异步操作，被写成继发关系。这样比较耗时，因为只有getFoo完成以后，才执行getBar，完全可以让它们同时触发。
```javascript
// 写法一
let [foo, bar] = await Promise.all([getFoo(), getBar()])

// 写法二
let fooPromise = getFoo()
let barPromise = getBar()
let foo = await fooPromise
let bar = await barPromise
```
3. await命令只能用在async函数内，如果用在普通函数中，就会报错。
```javascript
async function dbFuc(){
  let docs = [{}, {}, {}]

  // 报错
  docs.forEach(function (doc){
    await db.post(doc)
  })
}
```
上面代码会报错，因为await用在了普通函数中了。但是，如果将forEach方法的参数改成async函数，也有问题。
```javascript
function dbFuc(){ //这里不需要async
  let docs = [{}, {}, {}]

  // 可能得到错误的结果
  docs.forEach(async function(doc){
    await db.post(doc)
  })
}
```
上面代码可能不会正常工作，原因是这时三个db.post操作将是并发执行，也就是同时执行，而不是继发执行。正确的写法是采用for循环。
```javascript
async function dbFuc(){
  let docs = [{}, {}, {}]

  for(let doc of docs){
    await db.post(doc)
  }
}
```
如果确实希望多个请求并发执行，可以使用Promise.all方法。当三个请求都会resolved时，下面两种写法效果相同。
```javascript
async function dbFuc(db) {
  let docs = [{}, {}, {}]
  let promises = docs.map((doc) => {return db.post(doc)})

  let results = await Promise.all(promises)
  console.log(results)
}

// 或者使用下面的写法

async function dbFuc(db) {
  let docs = [{}, {}, {}]
  let promises = docs.map((doc) => {return db.post(doc)})

  let results = []
  for(let promise of promises){
    results.push(await promise)
  }
  console.log(promises)
}
```
# 4.异步遍历器

